name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: set up chrome-stable
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: set up edge-stable
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: set up firefox-stable
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest-esr

      - name: Run specific testNG.xml file
        run: mvn clean test -D suiteXmlFile=testNG.xml